FROM almalinux
ADD https://raw.githubusercontent.com/trussworks/terraform-aws-s3-private-bucket/main/main.tf /tmp/
# a random link from github
ADD apache-tomcat-9.0.73-embed.tar.gz /tmp/
# Add can unzip or untar the file